include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_bool_literals_in_conditional_expressions
    - comment_references
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_relative_imports
    - use_super_parameters
