name: zenstream
description: "A simple theatre client - Zenstream"

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.0
  bitsdojo_window: ^0.1.6
  smooth_page_indicator: ^1.2.0+3
  shared_preferences: ^2.3.3
  http: ^0.13.3
  platform: ^3.0.0
  device_info_plus: ^11.2.0
  logger: ^1.0.0
  cached_network_image: ^3.3.1
  flutter_blurhash: ^0.8.2
  dio: ^4.0.0
  universal_html: ^2.0.6
  solar_icons: ^0.0.5
  json_theme_plus: ^6.7.2
  iconamoon: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.2"

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
  windows:
    generate: true
    icon_size: 64
  macos:
    generate: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/icon.png
    - .env
    - themes/light.json
    - themes/dark.json

fonts:
  - family: GoNotoKurrent
    fonts:
      - asset: fonts/GoNotoKurrent-Bold.ttf
        fontWeight: 700
      - asset: fonts/GoNotoKurrent-Regular.ttf
        fontWeight: 400

  - family: Nunito
    fonts:
      - asset: fonts/Nunito-Medium.ttf
        fontWeight: 500
